VOCAB = [
"a/ab + ablative from, by                         ",
"absum, abesse, Afui I am absent, I am away       ",
"accedO, accedere, accessi I approach             ",
"accendO, accendere, accendi I light              ",
"accipiO, accipere, accepi I accept, receive      ",
"accurrO, accurrere, accurri I run to             ",
"accesO, accOsare, accusavi I accuse              ",
"ad + accusative to                               ",
"addo, addere, addidi I add                       ",
"adeo, adire, adii I go to, approach              ",
"adsum, adesse, adfui I am present                ",
"advenid, advenire, adveni I arrive               ",
"aedes, aedium, fpl. house                        ",
"aedificium, aedificii, n. building               ",
"aedificd, aedificare, aedificavi I build         ",
"aegre reluctantly                                ",
"aequus-a-um equal, fair                          ",
"age! come on!                                    ",
"ager, agri, m. field                             ",
"agricola, agricolae, m. farmer                   ",
"ago, agere, egi I do; I drive                    ",
"alius, alia, aliud other                         ",
"alter, altera, alterum one or the other (of two) ",
"altus-a-um high, deep                            ",
"ambulO, ambulare, ambulavi I walk                ",
"amicus, amid, m. friend                          ",
"amO, amare, amAvi I love                         ",
"amor, amOris, m. love                            ",
"animus, animi, m. mind                           ",
"annus, anni, m. year                             ",
"ante + accusative before                         ",
"Anxius-a-um anxious                              ",
"apertus-a-um open                                ",
"aperio, aperire, aperui I open                   ",
"aqua, aquae, f. water                            ",
"arbor, arboris, f. tree                          ",
"ArdeO, ardere, Arsi I am on fire                 ",
"Ardens, Ardentis burning                         ",
"argentum, argent', n. silver, money              ",
"arma, armOrum, n.pl. arms                        ",
"armatus-a-um armed                               ",
"aro, arAre, aravi I plough                       ",
"aratrum, arAtri, n. plough                       ",
"arrideO, arridere, arrisi I smile at             ",
"ascendO, ascendere, ascendi I climb, board       ",
"attendO, attendere, attend I attend             ",
"attonitus-a-um astonished                        ",
"audax, audacis bold                              ",
"aude6, audere I dare                             ",
"audio, audire, audivi I hear, listen to          ",
"angel), augere, auxi I increase                  ",
"aut or                                          ",
"aut    aut either ... or                        ",
"auxilium, auxilii, n. help                      ",
"bellum, belli, n. war                           ",
"bene well                                       ",
"benignus-a-um kind                               ",
"bibO, bibere, bibi I drink                       ",
"bonus-a-um good                                  ",
"brevis, breve short                             ",
"cado, cadere, cecidi I fall                      ",
"caedO, caedere, cecidi I beat; I kill            ",
"caelum, caeli, n. sky, heaven ",
"calidus-a-um hot",
"campus, campi, m. plain ",
"capiO, capere, cepi I take ",
"canis, canis, c. dog",
"capsula, capsulae, f box ",
"caput, capitis, n. head ",
"carmen, carminis, n. song ",
"carus-a-um dear",
"casa, casae,f house",
"castra, castrOrum, n. p/. camp ",
"caupona, caupOnae,f inn ",
"cecidi see cado",
"cedO, cedere, cessi I yield, give way",
"celebrO, celebrare, celebravi I celebrate",
"celer, celeris, celere quick ",
"aria, cenae, f dinner",
"cenare, cenavi I dine ",
"centuriO, centuriOnis, m. centurion",
"cessO, cessare, cessavi I tarry, idle",
"ceteri, ceterae, cetera the rest, the others",
"cibus, cibi, m. food",
"circum + accusative around ",
"civis, civis, m. citizen",
"clamo, clAmAre, clamavi I shout ",
"clamor, clAmoris, m. shout ",
"clarus-a-um clear; famous ",
"claudO, claudere, clausi I shut ",
"clausus-a-um shut",
"cognosco, cognOscere, cognOvi I get to know, learn ",
"collis, collis, m. hill",
"cold, colere, colui I cultivate; I revere",
"comes, comitis, c. companion ",
"cOmis, come friendly",
"commoved, commovere, commOvi I move ",
"commOtus-a-um moved, upset",
"compleo, complere, complevi I fill",
"compOnO, compOnere, composul I put together, compose",
"condo, condere, condidi I found ",
"condfico, condficere, condfixi I hire ",
"confectus-a-um finished; worn out",
"cOnficiO, dinficere, cOnfeci I finish",
"coniciO, conicere, conieci I throw, hurl",
"cOnscendo, cOnscendere, contend' I board ",
"cOnsisto, cOnsistere, cOnstiti I halt, stand ",
"cOnspicio, cOnspicere, conspexi I catch sight of ",
"cOnsilium, cOnsilii, n. plan; advice",
"cOnstituo, cOnstituere, cOnstitui I decide",
"consul, cOnsulis, m. consul",
"contendo, contendere, contend' I march, hasten; I compete",
"contra + accusative against",
"conveniO, convenire, conveni I come together ",
"convocO, convocare, convocAvi I call together ",
"corpus, corporis, n. body",
"cotidie daily, every day ",
"eras tomorrow",
"credo, caedere, credidi + dative I believe",
"culina, culinae, f. kitchen ",
"cum (conjunction) when ",
"cum + ablative with",
"cupid, cupere, cupivi I desire, wish",
"cur? why?                                       ",
"femina, feminae, f. woman ",
"cfira, corae, f. care                           ",
"ferre, tuli I carry, bear",
"ferrum, feria, n. iron; sword",
"cursus, curses, m. course                       ",
"fessus-a-um tired",
"de + ablative about; down from                  ",
"festino, festinfire, festinavi I hurry",
"debee, debere, debut I ought, must              ",
"!Ilia, filiae, f. daughter ",
"decide, decidere, decidi I fall down            ",
"lint's, fill!, m. son",
"deinde then, next                               ",
"flamma, flammae, f. flame ",
"denique finally                                 ",
"Ref), flere, flevi I weep",
"flOris, m. flower",
"descendO, descendere, descend! I descend          ",
"flumen, fluminis, n. river ",
"deserO, deserere, deserul I desert ",
"desper6, desperare, desperavi I despair         ",
"fluvius, fluvii, m. river ",
"dens, del, m. god                               ",
"fens, fontis, m. spring                                                 ",
"fortis, forte brave",
"dice', dicere, dixi I say, tell",
"dies, die!, m. day                             ",
"fortiter bravely                                                ",
"forum, for!, n. forum ",
"difficilis, difficile difficult",
"frater, fratris, m. brother ",
"diffugiO, diffugere, diffugi I flee away ",
"restra in vain",
"diligenter carefully",
"fugio, fugere, fag! I flee ",
"dimittere, dimes! I send away, dismiss ",
"discedO, discedere, discessi I go away, leave   ",
"gaudeO, gaudere I rejoice ",
"discipulus, discipull, m. pupil                 ",
"gaudium, gaudil, n. joy",
"discO, discere, didici I learn                  ",
"gerO, gerere, gessi I carry, wear; I do ",
"diii for a long time                            ",
"gladius, gladii, m. sword",
"do, dare, dedi I give                           ",
"glOria, glOriae, f. glory ",
"doceO, docere, docu! I teach                    ",
"gradus, grades, m. step ",
"doctus-a-um learned                             ",
"dominus, domini, m. master, lord                ",
"gratiae, gratiarum, /pl. thanks",
"domus, domes, f. home                           ",
"gratifis agere to give thanks to",
"domi at home                                    ",
"gravis, grave heavy; serious ",
"dormio, dormire, dormivi I sleep                ",
"habeO, habere, habui I have",
"dum while                                       ",
"habitO, habitare, habitavi I live in, inhabit ",
"dilcere, &al I lead                        ",
"hasta, hastae, f. spear",
"dfirus-a-um hard, tough                         ",
"hic, haec, hoc this",
"dux, ducis, c. leader                           ",
"hic here",
"hiems, hiemis, f. winter ",
"e, ex + ablative out of, from                   ",
"hodie today",
"ebrius-a-um drunk                               ",
"horn-6, hominis, c. human being, man",
"ecce! look!                                     ",
"hOra, hOrae,f. hour ",
"edO, esse, edi I eat                            ",
"hortus, horti, in. garden ",
"effugio, effugere, effugi 1 escape              ",
"hostis, hostis, c. enemy ",
"ego I                                           ",
"hiic hither, to here",
"emO, emere, em! I buy                           ",
"iaceO, iacere, iacui I lie ",
"enim for                                        ",
"iaciO, iacere, ieci I throw ",
"eel, ire, ii Igo                                ",
"iaculum, iacult, n. javelin ",
"eo (adverb) thither, there                      ",
"lam now, already",
"epistola, epistolae, f. letter                  ",
"ianua, ianuae, f. door ",
"equito, equitare, equitavi I ride               ",
"ibi there",
"equus, equi, m. horse                           ",
"igitur therefore, and so ",
"eripiO, eripere, eripu! I snatch away, rescue   ",
"ignis, ignis, m. fire",
"erre), errare, erravi I wander; I err, am wrong ",
"ille, illa, illud that; he, she ",
"et and; et ... et both . . . and",
"illac thither; to there ",
"etiam even; also",
"imago, imaginis, f. picture",
"evade', evadere, evasI I escape",
"imperium, imperil, n. order; empire ",
"excite', excitare, excitavi 1 wake, rouse ",
"impere, imperare, imperavi + dative I order ",
"in + accusative into, to",
"exercitus, exercitus, m. army",
"exspectO, exspectare, exspectilvi I wait for ",
"incendO, incendere, incendi I set on fire",
"incipiO, incipere, incepi I begin",
"fabula, fabulae, f. story                       ",
"inde thence; from there ",
"facilis, facile easy                            ",
"induO, induere, indul I put on",
"facile easily                                   ",
"ineti, Wire, !nil I go into, enter",
"facie, facere, feel I do, I make                ",
"infelix, infelicis unlucky, ill-starred",
"familia, familiae, / household, family          ",
"ingens, ingentis huge",
"inquit he, she said                            ",
"miles, militis, m. soldier",
"inspicid, inspicere, inspexi I look at         ",
"milito, militare, militavi I serve (as a soldier) ",
"insula, insulae, f island; block of flats      ",
"miser, misera, miserum wretched, miserable ",
"intellego, intellegere, intellexi I understand ",
"mittd, mittere, misi I send",
"intente intently                               ",
"moned, monere, monui I warn, advise ",
"inter + accusative among; between              ",
"mOns, montis, m. mountain",
"intereA meanwhile                              ",
"mora, morae, f delay",
"interficio, interficere, interfeci I kill      ",
"mors, mortis, f death",
"intre, intrare, intravi I enter                ",
"mortuus-a-um dead",
"invenid, invenire, inveni I find               ",
"moved, movere, mOvi I move",
"Ira, irae,f anger                             ",
"mox soon",
"iratus-a-um angry                             ",
"multus-a-um much; many",
"is, ea, id he, she, it; that                  ",
"mums, mini, m. wall",
"itaque and so .                               ",
"nam for",
"iter, itineris, n. journey                    ",
"narro, narrare, narravi I tell, relate ",
"iterum again                                  ",
"natus-a-um born, old",
"iubed, iubere, iussi I order                  ",
"nauta, nautae, m. sailor ",
"Iuppiter, Iovis, m. Jupiter                   ",
"nfivigo, navigare, navigavi I sail",
"iuvenis, iuvenis, m. young man                ",
"navis, navis, f. ship",
"iuvo, iuvare, itivi I help                    ",
"labor, laboris, m. work; suffering            ",
"nec, neque nor; and not ",
"laboro, laborare, labdrAvi I work             ",
"nec, neque ... nec, neque neither . . . nor",
"lacrima, lacrimae, f. tear                    ",
"nem() no one",
"lacrimd, lacrimare, lacrimfivi I weep         ",
"nesciii, nescire, nescivi I do not know",
"laetus-a-um happy                             ",
"nihil nothing",
"latus-a-um wide                               ",
"nomen, no:minis, n. name ",
"Latine in Latin                                ",
"ndmine by name; called                              ",
"laude, laudare, laudAvi I praise              ",
"non not",
"laus, laudis, f praise                         ",
"nonne (indicates question) ",
"lautus-a-um elegant, smart                     ",
"rids we",
"lave, lavare, lay! I wash                     ",
"ndscd, ndscere, nOvi I get to know, learn",
"Legit', legiOnis,f. legion                     ",
"noster, nostra, nostrum our ",
"lego, legere, leg! I read                      ",
"novus-a-um new",
"lente slowly                                   ",
"nox, noctis, I night",
"lex, legis,f law                               ",
"nullus-a-um no",
"fiber, libri, m. book                          ",
"numerus, numeri, m. number ",
"liber, libera, liberum free                    ",
"numquam never",
"liberd, liberAre, liberavi I free              ",
"nunc now",
"littera, litterae, f. letter                   ",
"nfintid, nfintiare, nfintiAvi I announce",
"litterae, litterarum, f.pl. literature         ",
"nimtius, ntintii, m. message; messenger",
"litus, litoris, n. shore",
"loculi, loculorum, m.pl. satchel               ",
"obsided, obsidere, obsedi I besiege ",
"locus, loci, m. place                          ",
"occupAtus-a-um busy",
"longus-a-um long                               ",
"oculus, oculi, m. eye ",
"longe far                                      ",
"Ohm once, at some time ",
"IMO, Mere, Ifni I play                         ",
"omnis, omne all",
"lulus, Ifli, m. game; school                   ",
"oppidum, oppidi, n. town ",
"Mita, Itinae, f moon                           ",
"opus, operis, n. work ",
"lupus, lupi, m. wolf                           ",
"oraculum, oraculi, n. oracle",
"Ifix, liicis,f. light                          ",
"615,o:ware, Oravi I beg ",
"Oratid, Oratidnis, f. speech",
"magister, magistri, m. (school) master         ",
"orator, Oratdris, m. speaker, orator",
"magistratus, magistrattis, m. magistrate       ",
"ostendo, ostendere, ostendi I show",
"magnifice magnificently",
"magnus-a-um big, great                         ",
"panis, pAnis, m. bread ",
"malus-a-um bad                                 ",
"paratus-a-um ready",
"male badly                                     ",
"parens, parentis, c. parent",
"mane early                                     ",
"pared, parere, parui + dative I obey",
"maned, manere, mansi I remain, stay            ",
"part), parare, parAvi I prepare ",
"manus, mantis,/ hand; band, group              ",
"pars, partis, f. part",
"mare, marls, n. sea                            ",
"parvus-a-um small",
"mater, matris,f mother                         ",
"pater, patris, m. father ",
"medius-a-um middle                             ",
"patria, patriae, f. fatherland ",
"memoria, memoriae, f memory                    ",
"panel, paucae, pauca few ",
"meridies, meridiei, m. midday                  ",
"paulisper for a short time ",
"meus, mea, meum my                             ",
"pauper, pauperis poor",
"pax, pAcis, f. peace                         ",
"relinquO, relinquere, reliqu! I leave ",
"pellO, pellere, pepuli I drive               ",
"remigo, remigare, remigavi I row ",
"per + accusative through                     ",
"res, rei,/ thing, matter, affair",
"pereo, perire, peril I perish, die           ",
"resists, resistere, restiti + dative I resist ",
"periculum, periculi, n. danger               ",
"respondeo, respondere, respondi I answer ",
"persuadeo, persuAdere, persuasi + dative I   ",
"respublica, reipfiblicae, f. state, republic ",
"retineO, retinere, retinui I hold back, restrain",
"pervenio, pervenire, perveni I reach, get to ",
"rex, regis, m. king",
"pes, pedis, m. foot                          ",
"rides, ridere, risi I laugh, smile ",
"petO, petere, petivi I seek, chase           ",
"ripa, ripae, f. bank",
"pictiira, pictfirae, f. picture              ",
"rogO, rogare, rogavi I ask, I ask for ",
"pila, pilae, f. ball                         ",
"rue*, mere, rui I rush",
"places, placere, placul + dative I please    ",
"rtirsus again",
"plane clearly                                ",
"sacer, sacra, sacrum sacred ",
"plaudo, plaudere, plausi I clap, applaud ",
"sacrificium, sacrificil, n. sacrifice ",
"plenus-a-um full",
"saepe often",
"poeta, poetae, m. poet",
"saevus-a-um savage",
"pOnO, pOnere, posui I place, put",
"salfitis, f. greetings",
"populus, populi, m. people",
"porta, portae, f. gate                       ",
"salfit6, saliitare, salfitavi I greet ",
"salve! greetings!",
"porto, portare, portavi I carry",
"saxum, saxi, n. rock",
"portus, portiis, m. port, harbour",
"schola, scholae, f. lecture; school ",
"possum, posse, potui I can, am able ",
"scelestus-a-um criminal, wicked ",
"post + accusative after; behind",
"sciO, scire, scivi I know",
"postea afterwards",
"scribo, scribere,scripsi I write, draw ",
"posterus-a-um next",
"scriba, scribae, m. secretary",
"postridie the next day",
"princeps, principis, m. chief. prince        ",
"sed but",
"sedeo, sedere, 0[11 I sit",
"primus-a-um first",
"sells, sellae, f. chair",
"primum (adverb) first                        ",
"semper always",
"pro + ablative in front of; on behalf of ",
"senator, senatoris, m. senator ",
"procedO, prOcedere, processi I advance, go on",
"senex, senis, m. old man",
"procul far                                   ",
"proelium, proelii, n. battle",
"servO, servare, servavi I save ",
"prohibeO, prohibere, prohibui I prevent      ",
"servus, servi, m. slave",
"prOmitto, prOmittere, prOmisi I promise      ",
"severus-a-um severe",
"prope + accusative near                      ",
"si if",
"prudens, prfidentis sensible",
"sic thus",
"puella, puellae, f. girl                     ",
"signum, signi, n. signal; standard ",
"puer, pueri, m. boy; child",
"silva, silvae, f. wood",
"pugna, pugnae, f. battle",
"simul at the same time",
"pugno, pugnare, pugnavi I fight",
"sine + ablative without",
"pulcher, pulchra, pulchrum beautiful         ",
"sill, soils, m. sun",
"plink), pi:mire, pfinivi I punish",
"solus-a-um alone",
"somnus, somni, m. sleep",
"quae who (feminine)                          ",
"soror, sorforis, f. sister",
"quaero, quaerere, quaesivi I look for        ",
"specto, spectare, spectAvl I look at ",
"quandO? when?                                ",
"spelt, sperAre, speravi I hope ",
"quantus-a-um? how great?                     ",
"spes, spec, f. hope",
"-que and                                     ",
"splendidus-a-um splendid",
"qui who (masculine)                          ",
"statim at once",
"quiescO, quiescere I rest                    ",
"sto, stare, stet! I stand",
"quis? quid? who? what?                       ",
"strenue strenously",
"quidam, quaedam, quoddam a certain           ",
"studeO , studere,studui + dative I study, am keen on ",
"quo? whither? where to?                      ",
"studium, studii, n. study, enthusiasm",
"quod because                                 ",
"sub + ablative under",
"quoque also                                  ",
"subitO suddenly",
"subsellium, subsellii, n. bench ",
"rapiO, rapere, rapui I snatch",
"sum, esse, fui I am",
"recitO, recitAre, recitAvi I recite, read aloud ",
"summus-a-um highest, greatest ",
"rtcte rightly, correctly",
"sumo, siimere, sumpsi I take up ",
"reddO, reddere, reddidi I give back, return ",
"redeo, redire, redii I go back, return       ",
"super + accusative above",
"regina, reginae, f. queen                    ",
"super6, superare, superavi I overcome, outdo ",
"regiO, regionis, f. region, district         ",
"surgO, surgere, surrexi I rise, get up",
"reg6, regere, rex! I rule                    ",
"tabula, tabulae, f. tablet",
"tace0, tacere, tacu! I am quiet           ",
"unde? whence, where from? ",
"tacitus-a-um quiet, silent                ",
"undique from all sides",
"tam so                                    ",
"onus-a-um one",
"tamen but, however                        ",
"urbs, urbis, f city",
"tandem at length                          ",
"uxor, uxOris, f. wife",
"tantus-a-um so great                      ",
"valde very",
"tempestas, tempestAtis, f. storm          ",
"vale! farewell",
"templum, templi, n. temple                ",
"valere iube0 I bid farewell, say goodbye ",
"tempt6, temptare, temptAvi I try, attempt ",
"vendO, vendere, vendidi I sell",
"tempus, temporis, n. time                 ",
"veni0, venire, veni I come ",
"teneO, tenere, tenni I hold               ",
"ventus, vent!, in. wind ",
"terra, terrae, f. land, earth             ",
"verbum, verb!, n. word ",
"terreO, terrere, terra! I frighten        ",
"verecundus-a-um shy",
"territus-a-um terrified                   ",
"versus, versus, in. verse ",
"time0, timere, time! I fear               ",
"verto, vertere, verti I turn ",
"timor, timOris, m. fear                   ",
"verus-a-um true",
"toga, togae, f. toga                      ",
"vesper, vesperis, m. evening ",
"tollO, tollere I raise                    ",
"vetus, veteris old",
"tOtus-a-um whole                          ",
"via, vise, f road, way",
"tradO, trAdere, tradidi I hand over       ",
"vicinus-a-um neighbouring; neighbour ",
"traho, trahere, Wild I drag               ",
"victor, victOris, rn. victor, winner",
"trans + accusative across                 ",
"villa, villae, f. country house ",
"transeO, transire, transii I cross        ",
"vino, vincere, vie! I conquer ",
"tristis, triste sad                        ",
"vinum, yin!, n. wine",
"to you                                     ",
"vir, virl, m. man, husband ",
"turba, turbae, f. crowd ",
"tutus-a-um safe                            ",
"vials, virile manly",
"turn then                                  ",
"v!s-ne? do you want?",
"tumultus, tumultus, m. riot, uproar        ",
"vita, vitae, f life",
"vivo, vivere, vixi I live",
"ubi? where                                 ",
"vocO, vocare, vocAvi I call ",
"ubi when                                   ",
"vox, vOcis, f. voice",
"ubique everywhere                          ",
"vulnus, vulneris, n. wound",
"ultimus-a-um furthest, last                ",
"vulnero, vulnerare, vulneravi I wound ",
"umquam ever                                ",
"vultus, vultfis, m. face, expression",
"unda, undae, f. wave",
]